"""Read-only reduction of verified analyzer002; no full32 raw replay claim."""
from pathlib import Path
import json,hashlib,math,statistics
here=Path(__file__).resolve().parent;repo=next(p for p in here.parents if(p/'robot/active_model.json').is_file());p=repo/'tmp/canonical_standing32_failure_analysis_root_002/analysis.json';x=json.loads(p.read_text())
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
observations={(s['sequence'],o['env'],o['body']):o for s in x['targeted_contact_samples']for o in s['observations']};events=[];residual=[]
for e in x['support_events']:
 s=e['sequence'];env=e['env'];assert len(e['missing_legs'])==1;body=e['missing_legs'][0]+'_tibia';prev=observations.get((s-1,env,body));cur=observations[(s,env,body)];nxt=observations.get((s+1,env,body));joints={}
 for name,a in cur['joints'].items():
  before=prev['joints'][name]if prev else None
  fd=(a['q']-before['q'])/.0025 if before else None
  if fd is not None:
   residual.append(abs(fd-a['interval_dq']));assert abs(fd-a['interval_dq'])<1e-10
  joints[name]={'q':a['q'],'sdk_endpoint':a['sdk_dq'],'sdk_previous':before['sdk_dq']if before else None,'angle_interval':a['interval_dq'],'recomputed_interval':fd,'sdk_endpoint_average':(a['sdk_dq']+before['sdk_dq'])/2 if before else None}
 patch=cur['raw_patches'];events.append({'env':env,'sequence':s,'time_s':e['time_s'],'body':body,'force_n':e['all_foot_force_norm_n'],'before_force_n':math.sqrt(sum(t*t for t in prev['stored_toe_force_world_n']))if prev else None,'after_force_n':math.sqrt(sum(t*t for t in nxt['stored_toe_force_world_n']))if nxt else None,'inactive_patch_count':sum(a['inactive_zero_normal']for a in patch),'patch_count':len(patch),'joints':joints,'all_six_force_zero':all(a==0 for a in e['all_foot_force_norm_n']),'affected_leg_all_sdk_zero':all(a['sdk_dq']==0 for a in cur['joints'].values())})
tibia=[e['joints'][e['body']+'_pitch']for e in events];rms=lambda a:math.sqrt(sum(v*v for v in a)/len(a));rows=x['rates_400hz_float64_accumulation'];flat=[{'env':e['env'],'name':k,**v}for e in rows for k,v in e['joints'].items()]
summary={'schema':'canonical_solver_decision_evidence_v1','analyzer002_result_sha256':sha(p),'analyzer_runtime_sha256':x['self_sha256'],'analyzer_helper_sha256':x['helper_sha256'],'source_sha256':x['source_freeze_sha256'],'scope':'Independent reduction of analyzer002 derived result plus q-difference reconstruction on exported event-adjacent samples; full remote arrays not reread.','event_count':len(events),'all_events_single_toe_zero':all(sum(f==0 for f in e['force_n'])==1 for e in events),'all_events_128_inactive_slots':all(e['inactive_patch_count']==128 and e['patch_count']==128 for e in events),'all_six_zero_events':sum(e['all_six_force_zero']for e in events),'affected_leg_all_sdk_zero_events':sum(e['affected_leg_all_sdk_zero']for e in events),'event_joint_interval_reconstructions':len(residual),'max_interval_reconstruction_error':max(residual),'other_foot_minimum_n':min(f for e in events for f in e['force_n']if f>0),'event_tibia_endpoint_abs_max':max(abs(a['sdk_endpoint'])for a in tibia),'event_tibia_interval_abs_max':max(abs(a['angle_interval'])for a in tibia),'event_tibia_interval_rms':rms([a['angle_interval']for a in tibia]),'event_tibia_residual_rms_vs_post_sdk':rms([a['angle_interval']-a['sdk_endpoint']for a in tibia]),'event_tibia_residual_rms_vs_endpoint_average':rms([a['angle_interval']-a['sdk_endpoint_average']for a in tibia]),'worst_whole_window_400hz_sdk':max(flat,key=lambda a:a['sdk_rms_400hz']),'worst_whole_window_400hz_interval':max(flat,key=lambda a:a['interval_rms_400hz']),'counterexamples_interval_exceeds_sdk_400hz':[a for a in sorted(flat,key=lambda a:a['interval_rms_400hz']-a['sdk_rms_400hz'],reverse=True)[:5]],'example_event':events[0],'max_reset_relative_translation_delta_m':max(e['translated_link_position_max_abs_delta_from_env0_m']for e in x['reset_comparison']),'env0_reset_equal_single':x['env0_reset_equal_single'],'env0_native_trajectory_equal_single':x['env0_substep_parity_to_single'],'all_native_replica_inertial_limits_equal':all(x['native_replicas_equal_env0'].values()),'events':events,'no_causal_claim':True,'GPU_calls':0}
(here/'EVIDENCE.json').write_text(json.dumps(summary,indent=2,allow_nan=False)+'\n');print(json.dumps({k:v for k,v in summary.items()if k not in ['events','counterexamples_interval_exceeds_sdk_400hz']},indent=2))
