from pathlib import Path
import hashlib,json,numpy as np
ROOT=Path('/Users/andreboufama/Documents/CUPI/HEXAPOD');OUT=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
review=ROOT/'tmp/reference_learning_train001_failure_review';consumer=ROOT/'tmp/reference_moving_ppo_003'
assert sha(consumer/'FREEZE_SHA256.json')=='fd9bef87dda976f9b229e7541408d24e674245ca2c51231dfce9075b81d38334'
for base in (review,consumer):
 for rel,bound in json.loads((base/'FREEZE_SHA256.json').read_text()).items():assert sha(base/rel)==bound
r=json.loads((review/'report.json').read_text());raw=ROOT/r['input_root']
for rel,bound in r['input_sha256'].items():assert sha(raw/rel)==bound
with np.load(raw/'run/train_10/raw/physics_substeps.npz') as trace:
 names=trace['joint_names'].tolist();assert names[17]=='revolute_2_1'
q=np.asarray(r['reset_contract_checks']['reset_target_rad'],np.float32)
assert len(names)==len(q)==18 and len(set(names))==18
rows=r['timeout_rows'];other=[i for i in range(32) if i not in rows]
epochs=[dict(id='initial',at_control=0,rows=list(range(32))),dict(id='full_repeat_1',at_control=200,rows=list(range(32))),dict(id='mixed_original_timeout26',at_control=400,rows=rows),dict(id='mixed_complement6',at_control=600,rows=other),dict(id='full_repeat_2',at_control=800,rows=list(range(32)))]
plan=dict(schema='reset_initialization_diagnostic_v1',status='CPU_preparation_no_runtime_admission',source009_manifest_sha256='04942c62de1f557d8f117f648f990b6dac69443d61c546529d05a4e2a7f0e01e',consumer003_freeze_sha256=sha(consumer/'FREEZE_SHA256.json'),failure_review_freeze_sha256=sha(review/'FREEZE_SHA256.json'),failure_report_sha256=sha(review/'report.json'),input_sha256=r['input_sha256'],joint_names_runtime=names,recorded_failure=dict(row=8,joint='revolute_2_1',requested_final8_peak_nm=r['failed_joint']['last_eight_substep_peak_nm'],reset_q_rad=q.tolist()),arms=[dict(id='recorded_failed_pose',distribution='point_mass_at_recorded_row8_reset_q_repeated_across32',q_rad=q.tolist()),dict(id='canonical_pose',distribution='point_mass_at_exact_named_imported_default',q_rad=None)],replicas=32,dt_s=.02,physics_dt_s=.0025,decimation=8,recovery_controls=200,max_controls_per_arm=1000,epochs=epochs,independent_arm_failures=True,first_failure_stops_arm=True,automatic_failed_row_retry=False,zero_residual=True,zero_command=True,actor_loaded=False,checkpoint_written=False,root_pose_or_velocity_intervention=False,reset_pose_scope='Joint positions and synchronized first executable target only, inside the original selected-row reset after it preserves its RNG draws/root/contact/sensor reset semantics.',hold_unselected='Continue unchanged canonical target; no reset/write to unselected root/joint/controller/clock/history state.',gates=dict(original_completion='Exactly200 controls,6 distal supports and none of original terminal_reasons including last8 requested torque>1.6, nonfoot/support/native flags.',applied_torque_max_Nm=float(np.float32(1.6)),requested_last8_max_Nm=1.6,native_termination_during_recovery='fatal',finite_and_fresh_every_step=True,target_budget_unchanged=True,post_completion_hold='All8substep requested<=1.6,6supports,no nonfoot/native. Stop arm on any failure.',full_recovery_requested_torque='Record all samples including reset peaks; no new blanket gate across excluded recovery period.',extra_diagnostics='Last100controls requested percentiles/torque distribution; rawq/qdot; all19bodyCOM and named foot forces; original quiet scorer reported separately, not substituted.'),fresh_standing=dict(replicas=32,controls=1000,source='Unchanged source009 physical+quiet standing; both arms require fresh same-source success.'),allocation=dict(phases=['standing','recorded_failed_pose','canonical_pose'],phase_wall_limit_s=600,outer_limit_s=1920,stop_grace_s=180,fallback_minutes=40,host_strategy='Reuse exact reviewed run_owned/owned_container and locks; only declared command/result phase adapter. Root binds next pause/unit after review. Independent A/B failure is explicit.'),interpretation='Reproduces the recorded joint reset vector and root convention, not the preceding2600-control actor/contact-cache history. Passing canonical arm does not prove stochastic-reset robustness or authorize training/production adoption.')
(OUT/'plan.json').write_text(json.dumps(plan,indent=2,allow_nan=False)+'\n')
(OUT/'INPUT_BINDINGS.json').write_text(json.dumps({'consumer':str(consumer),'failure_review':str(review),'raw':str(raw),'files':{str(p.relative_to(ROOT)):sha(p) for p in [consumer/'recovery.py',consumer/'moving_session.py',consumer/'learning_integrity.py',consumer/'SDK_RESET_API.json',ROOT/'tmp/reference_origin_adapter_002/sdk_write_api.json',ROOT/'tmp/reference_origin_adapter_002/sdk_target_setter_api.json',ROOT/'tmp/reference_learning_ppo_launch_001/launch_learning_ppo_spark.py',review/'report.json']}},indent=2)+'\n')
print('Bound32-row two-arm plan; timeout/complement=',len(rows),len(other))
