"""Compatibility shim for ``hexapod_rl.command_sampling``.

The implementation now lives in ``hexapod_env.command_sampling``
(``packages/hexapod_env/hexapod_env/command_sampling.py``). Names are re-exported
explicitly so ``importlib``-based entry-point resolution finds real attributes
here. Importing this module first imports the ``hexapod_rl`` package, whose
``__init__`` puts the workspace ``packages/`` directory on ``sys.path``; that
bootstrap is idempotent, so it is equally correct if it already ran.
"""

from hexapod_env.command_sampling import *  # noqa: F401,F403
from hexapod_env.command_sampling import (
    STANDING,
    LONGITUDINAL_ONLY,
    LATERAL_ONLY,
    YAW_ONLY,
    COMBINED,
    NUM_COMMAND_CATEGORIES,
    RECOVERY_FORWARD,
    RECOVERY_FORWARD_YAW,
    RECOVERY_FORWARD_LATERAL,
    RECOVERY_COMBINED,
    NUM_RECOVERY_CATEGORIES,
    RECOVERY_BUCKET_PERIOD,
    RECOVERY_FORWARD_BUCKETS,
    RECOVERY_FORWARD_YAW_BUCKETS,
    RECOVERY_FORWARD_LATERAL_BUCKETS,
    RECOVERY_COMBINED_BUCKETS,
    STAGE2_FORWARD,
    STAGE2_FORWARD_YAW,
    STAGE2_FORWARD_LATERAL,
    NUM_STAGE2_CATEGORIES,
    STAGE2_BUCKET_PERIOD,
    STAGE2_FORWARD_BUCKETS,
    STAGE2_FORWARD_YAW_BUCKETS,
    STAGE2_FORWARD_LATERAL_BUCKETS,
    STAGE2B_FORWARD,
    STAGE2B_LATERAL_ONLY,
    STAGE2B_FORWARD_LATERAL,
    STAGE2B_FORWARD_YAW,
    NUM_STAGE2B_CATEGORIES,
    STAGE2B_BUCKET_PERIOD,
    STAGE2B_FORWARD_BUCKETS,
    STAGE2B_LATERAL_ONLY_BUCKETS,
    STAGE2B_FORWARD_LATERAL_BUCKETS,
    STAGE2B_FORWARD_YAW_BUCKETS,
    STAGE2D_FORWARD,
    STAGE2D_OBLIQUE,
    STAGE2D_FORWARD_YAW,
    NUM_STAGE2D_CATEGORIES,
    STAGE2D_BUCKET_PERIOD,
    STAGE2D_OBLIQUE_BUCKETS,
    STAGE2D_FORWARD_BUCKETS,
    STAGE2D_FORWARD_YAW_BUCKETS,
    STAGE2E_STAND,
    STAGE2E_LATERAL,
    STAGE2E_FORWARD,
    STAGE2E_REVERSE,
    STAGE2E_YAW,
    STAGE2E_FORWARD_JOYSTICK,
    STAGE2E_REVERSE_JOYSTICK,
    NUM_STAGE2E_CATEGORIES,
    STAGE2E_BUCKET_PERIOD,
    body_to_navigation_frame,
    sample_velocity_command_mixture,
    sample_stage1_recovery_commands,
    sample_stage2_recovery_commands,
    sample_stage2b_lateral_acquisition_commands,
    sample_stage2d_oblique_homotopy_commands,
    sample_stage2e_joystick_transition_commands,
    normalized_signed_axis_progress,
    active_axis_gaussian_tracking_reward,
    sample_uniform_intervals,
    advance_resampling_timers,
)

__all__ = [
    "COMBINED",
    "LATERAL_ONLY",
    "LONGITUDINAL_ONLY",
    "NUM_COMMAND_CATEGORIES",
    "NUM_RECOVERY_CATEGORIES",
    "NUM_STAGE2_CATEGORIES",
    "NUM_STAGE2D_CATEGORIES",
    "NUM_STAGE2E_CATEGORIES",
    "RECOVERY_COMBINED",
    "RECOVERY_FORWARD",
    "RECOVERY_FORWARD_LATERAL",
    "RECOVERY_FORWARD_YAW",
    "STANDING",
    "STAGE2_FORWARD",
    "STAGE2_FORWARD_LATERAL",
    "STAGE2_FORWARD_YAW",
    "STAGE2D_FORWARD",
    "STAGE2D_FORWARD_YAW",
    "STAGE2D_OBLIQUE",
    "STAGE2E_FORWARD",
    "STAGE2E_FORWARD_JOYSTICK",
    "STAGE2E_LATERAL",
    "STAGE2E_REVERSE",
    "STAGE2E_REVERSE_JOYSTICK",
    "STAGE2E_STAND",
    "STAGE2E_YAW",
    "YAW_ONLY",
    "active_axis_gaussian_tracking_reward",
    "advance_resampling_timers",
    "body_to_navigation_frame",
    "normalized_signed_axis_progress",
    "sample_uniform_intervals",
    "sample_stage1_recovery_commands",
    "sample_stage2_recovery_commands",
    "sample_stage2d_oblique_homotopy_commands",
    "sample_stage2e_joystick_transition_commands",
    "sample_velocity_command_mixture",
]
