"""Derive compact interpretation strictly from completed original CPU analysis."""
from pathlib import Path
import collections,hashlib,json,math,sys
p=Path(sys.argv[1]);d=json.loads(p.read_text());assert d['used_raw_reverified_after_analysis']
idx={(s['sequence'],e['env'],e['body']):e for s in d['targeted_contact_samples']for e in s['observations']}
c=collections.Counter();other=[];grid={}
for r in d['replicas']:
 row=grid.setdefault(str(r['grid_xy_m'][1]),{'replicas':0,'passed':0,'missing_events':0});row['replicas']+=1;row['passed']+=r['pass'];row['missing_events']+=r['missing_support_substeps']
for event in d['support_events']:
 assert len(event['missing_legs'])==1
 leg=event['missing_legs'][0];l=['lf','lm','lr','rf','rm','rr'].index(leg);r=idx[event['sequence'],event['env'],leg+'_tibia'];ps=r['raw_patches'];c['missing_'+leg]+=1
 c['zero_missing_force']+=event['all_foot_force_norm_n'][l]==0;c['all_six_forces_zero']+=all(x==0 for x in event['all_foot_force_norm_n']);c['exact128_inactive_zero_patches']+=len(ps)==128 and all(x['inactive_zero_normal']and x['normal_force_n']==0 for x in ps);c['affected_leg_all_sdk_zero']+=all(v['sdk_dq']==0 for v in r['joints'].values());other.extend(v for j,v in enumerate(event['all_foot_force_norm_n'])if j!=l)
result={'analysis_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'audit_sha256':d['original_audit_sha256'],'source_freeze_sha256':d['source_freeze_sha256'],'host_error':d['host_error'],'pass_envs':[r['env']for r in d['replicas']if r['pass']],'events':len(d['support_events']),'event_summary':dict(c),'minimum_other_five_foot_force_n':min(other),'grid_y_summary':grid,'reset_max_translation_error_m':max(x['translated_link_position_max_abs_delta_from_env0_m']for x in d['reset_comparison']),'env0_reset_equal_single':d['env0_reset_equal_single'],'env0_dynamics_comparison':d['env0_substep_parity_to_single'],'native_properties_equal_across_replicas':d['native_replicas_equal_env0'],'targeted_projection_max_error_m':max(x['independent_shape_projection_max_error_m']for s in d['targeted_contact_samples']for x in s['observations']),'first_old_analyzer_float_precision_failure':{k:v for k,v in d['first_analyzer001_unrounded_product_mismatch'].items()if k!='differing_products'},'example_env11_RM':[{'sequence':s,'time_s':(s+1)*.0025,'force_n':math.sqrt(sum(x*x for x in idx[s,11,'rm_tibia']['stored_toe_force_world_n'])),'patches':len(idx[s,11,'rm_tibia']['raw_patches']),'joint':idx[s,11,'rm_tibia']['joints']['rm_tibia_pitch']}for s in [1603,1604,1605]],'named_rate_comparison':[{ 'env':e,'joint':j,'metrics':d['rates_400hz_float64_accumulation'][e]['joints'][j]}for e,j in [(0,'lm_tibia_pitch'),(2,'lm_tibia_pitch'),(18,'rm_tibia_pitch')]],'interpretation_limits':['Measured support loss is not proof of detached geometry;128inactive slots alone do not establish SDK root cause.','No all-six-zero signature in any event; affected-leg measured velocities are nonzero, inconsistent with proposed globalsleep signature.','Origin env0 also differs slightly from separate1env despite exact reset; worldtranslation alone is not isolated.','SDK/interval-rate differences contain both bias and transient angle motion; original SDK/support gates remain.','Controlled32/4 iteration diagnostic is a hypothesis test, not a demonstrated fix.']}
print(json.dumps(result,indent=2,allow_nan=False))
