from pathlib import Path
import json,hashlib,datetime
ROOT=Path(__file__).resolve().parents[2];D=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
write=lambda name,x:(D/name).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
asset=ROOT/'artifacts/mkii_updated_2026-09-10/usd_002/rs05_mass_corrected'
asset_map=json.loads((ROOT/'tmp/updated_native_inspection_003/ASSET_SHA256.json').read_text())
for name,digest in asset_map.items():
 assert sha(asset/name)==digest,(name,digest)
paths=['robot/active_model.json','robot/hexapod_mkii_updated_v1/model_rs05_mass_corrected.json','robot/hexapod_mkii_updated_v1/urdf/hexapod_updated_rs05_mass_corrected.urdf','docs/RS05_SPEC_REVIEW.md','docs/UPDATED_CAD_IMPORT.md','docs/PROJECT_SITE.md','packages/hexapod_core/hexapod_core/rs05_v2.json','tmp/updated_native_inspection_003/FREEZE_SHA256.json','tmp/canonical_native_inspection_terminal_003/audit.json','tmp/canonical_native_inspection_terminal_003/RAW_SHA256.json','tmp/canonical_native_inspection_terminal_003/run/inspection/state.json','tmp/canonical_native_inspection_terminal_003/run/inspection/native_readback.json','tmp/canonical_native_inspection_terminal_003/run/inspection/native_scene.json','tmp/canonical_native_inspection_terminal_003/run/inspection/samples.json']
write('INPUTS.json',{'scope':'Referenced immutable/native and current source documents; no large geometry or proprietary native SDK copied','repository_inputs':{n:sha(ROOT/n)for n in paths},'asset_directory':str(asset.relative_to(ROOT)),'asset_files':asset_map,'native_tensor_provider':{'path':'/isaac-sim/extscache/omni.physics.tensors-110.1.13+110.1.2.la64.r.cp312.u7f4/omni/physics/tensors/api.py','sha256':'b913fdb1a3c0cf04b62aa01d6ceaf7d96cfe577a510d0e02b71485018661c903'}})
state=json.loads((ROOT/paths[-4]).read_text()) if False else json.loads((ROOT/'tmp/canonical_native_inspection_terminal_003/run/inspection/state.json').read_text())
assert state['status']=='completed' and not state['errors']
write('PHASE_A_INPUT.json',{'status':'completed native import/representation inspection only','state_sha256':sha(ROOT/'tmp/canonical_native_inspection_terminal_003/run/inspection/state.json'),'explicit_steps':state['explicit_steps_completed'],'initialization_wall_s':state['initialization_wall_s'],'wall_s':state['wall_s'],'memory_bytes':state['memory_bytes'],'memory_interpretation':'CUDA free-memory is not total native allocation attribution. Root subsequently observed large reclaimable host cache and high host available memory; during-run RSS/host available/CUDA free/native scaling must be measured. No 109GB SDF claim.','physical_admission':False,'training_allowed':False})
servo=json.loads((D/'servo_candidate.json').read_text())
write('PROPOSED_CONTRACT.json',{'schema':'canonical_phase_b_cpu_proposal_v1','status':'ROOT_REVIEW_REQUIRED_BEFORE_NEW_NATIVE_SOURCE_ADMISSION','training_allowed':False,'hardware_qualified':False,'model_sha256':'7126935b35398d2a7f03271335a8a1b8f2059354af2b19d9474f22b8e73e4881','physics':{'dt_s':.0025,'control_decimation':8,'root':'floating','self_collision':'preserve authored true','colliders':'preserve exact153SDF','proposed_external_forces_every_iteration':True,'other_solver_settings':'inherit actual003 and read back; no implicit prior C settings'},'first_native_experiment':{'gravity':[0,0,0],'ground':False,'position_drives':False,'baseline_seconds':.1,'reset_coordinate_cases':'Each of18 names at+/-0.01rad, cold named-order write/read/FK; no full-range physical sweep','pulse_cases':'Each of18 names at+/-0.02Nm, eight2.5ms substeps, cold baseline per case','pulse_nm':.02,'pulse_steps':8,'recovery_zero_effort_seconds':.1,'diagnostic_limits':{'requested_nm':.1,'joint_displacement_rad':.05,'joint_velocity_rad_s':2.},'native_effort_readback_is':'actuation input, separately from projected reaction and full joint wrench; not hardware motor measurement'},'servo_candidate':servo,'provisional_motor':{'output_side':True,'numerical_cap_nm':1.6,'assumed_bus_voltage_v':48.,'speed_envelope':'min(1.6, piecewise interpolated manufacturer48Vcurve(abs(output_speed)))','speed_rpm':[0,70,275,340,450,477,480],'torque_nm':[5.5,5.5,4,3,1.6,.5,0],'braking':'same absolute-speed bound, explicitly unvalidated','burst_authority':False,'added_armature':0,'added_friction':0,'latency_model_s':0,'thermal_model':None,'hardware_current_model':None,'semantics':'Unmodeled does not mean identifiedzero; cap1.6 is not continuous-stall certification'},'next_standing':{'neutral_q_rad':0,'reset_plate_height_m':.08161109101311194,'cold_order':[1,32],'controls':1000,'requested_applied_capture_hz':400,'gate':'Existing actuator/quiet/no-nonfoot/no-termination criteria; new geometry-specific foot classifier and height contracts authored before run'},'scratch_smoke':{'fresh_network':True,'load_old_checkpoint':False,'replicas':32,'steps_per_update':24,'updates':2,'required':'new model-bound observation/action/reset/termination contract; valid standing; actual1-to32 memory/timing evidence; strictfreshreload'},'deferred':'hardware transfer, burstthermal model, fullomni/terrain qualification and larger allocation'})
write('FABLE_REVIEW.json',{'session_id':'556cc46a-6aba-49a0-8459-e5887c0936b4','model':'claude-fable-5-1','effort':'max','tools_disabled':True,'final_sha256':sha(D/'fable/fable_final.json'),'adopted':['Provisional simulation learning need not wait for hardware identification','Floating-root no-ground coordinate/effort seam before servo/standing','Mass/coupling baseline and separate input/reaction evidence','Explicit speed envelope and executed-target observation','Actual memory/throughput before scaling'], 'independent_corrections':['Zero-G/no-drives does not guarantee quiescence with self-contact/constraint warmup','Momentum need not startzero and rootvelocity is not whole-body momentum','Pulse acceleration uses full M^-1 tau, not diagonal M_jj','Near-limit scalar readback is not a collision-safe integrated range sweep','Proposed100rpm knee/rolloff is not a verified vendor map; use exact documentedcurve with numerical1.6cap and explicit braking qualification','PD is a chosen simulationinterface, not evidence of installed actuator loop behavior','Baseline collision problems do not automatically authorize collider pruning'], 'actual003_update':'Returned q/dq/rootmotionzero in eight actual steps supports that short baseline only; it does not prove longer loaded quiet. Source and state exact hashes in INPUTS.'})
